# Generated by Django 2.2.7 on 2019-12-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('folguista', models.BooleanField(default=False, verbose_name='folguista')),
                ('feirista', models.BooleanField(default=False, verbose_name='feirista')),
                ('turno', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('turno', models.CharField(choices=[('NDA', 'NDA'), ('Madrugada - A', 'Madrugada - A'), ('Manhã - B', 'Manhã - B'), ('Tarde - C', 'Tarde - C'), ('Noite - D', 'Noite - D')], max_length=20, primary_key=True, serialize=False)),
                ('funcionario', models.ManyToManyField(to='funcionario.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='PlantaoExtra',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantao_estra', to='funcionario.Plantao')),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantao_folga', to='funcionario.Plantao')),
            ],
        ),
    ]
