# Generated by Django 2.2.7 on 2019-12-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantaoextra',
            name='plantao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantao_extra', to='funcionario.Plantao'),
        ),
    ]
