# Generated by Django 2.2 on 2019-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20191227_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
